### ISSUE TITLE
Add support for the OpenAPI Link Object

### ISSUE THREAD

**Issue by mbarnach** [mattpolzin/OpenAPIKit#102]
Prerequisite: https://github.com/mattpolzin/OpenAPIKit/issues/104

When adding a `Link` to an OpenAPI document, the parser returns an error. It considers that the Link is a "Vendor Extension" and should starts with `x-`.
The following example, from [OpenAPI documentation](https://swagger.io/docs/specification/links/), returns the error.

```
openapi: 3.0.0
info:
  version: 0.0.0
  title: Links example
paths:
    /users:
        post:
            summary: Creates a user and returns the user ID
            operationId: createUser
            requestBody:
                required: true
                description: A JSON object that contains the user name and age.
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/User'
            responses:
                '201':
                    description: Created
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        format: int64
                                        description: ID of the created user.
            # -----------------------------------------------------
            # Links
            # -----------------------------------------------------
            links:
                GetUserByUserId:   # <---- arbitrary name for the link
                    operationId: getUser
                    # or
                    # operationRef: '#/paths/~1users~1{userId}/get'
                    parameters:
                        userId: '$response.body#/id'
                    description: >
                        The `id` value returned in the response can be used as
                        the `userId` parameter in `GET /users/{userId}`.
            # -----------------------------------------------------
    /users/{userId}:
        get:
            summary: Gets a user by ID
            operationId: getUser
            parameters:
                - in: path
                  name: userId
                  required: true
                  schema:
                    type: integer
                    format: int64
            responses:
                '200':
                    description: A User object
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/User'
components:
    schemas:
        User:
            type: object
            properties:
                id:
                    type: integer
                    format: int64
                    readOnly: true
                name:
                    type: string
```

**Comment by mattpolzin** [comment]
Thanks for the report. Links are not yet supported because I have not had time to figure out how best and most safely to represent OpenAPI [**Runtime Expressions**](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#runtime-expressions) in OpenAPIKit.

The Link Object is documented as a missing part of OpenAPIKit under the [Specification Coverage](https://github.com/mattpolzin/OpenAPIKit/blob/master/documentation/specification_coverage.md#link-object). The Callback Object is [also unimplemented](https://github.com/mattpolzin/OpenAPIKit/blob/master/documentation/specification_coverage.md#callback-object) because it depends on Runtime Expressions.

I'll leave this ticket open since I would like to track these missing pieces as issues anyway but I will rename the ticket as an "enhancement".

**Comment by mbarnach** [comment]
Would it be doable, in the meantime, to ignore it completely, with a warning? Otherwise anyone will have to remove it completely from the document.

**Comment by mattpolzin** [comment]
> Would it be doable, in the meantime, to ignore it completely, with a warning?
That is a great middle-ground on this issue. I am putting together a branch that ignores it right now; that's actually how decoding used to work (as its the default behavior of `Codable`) until I added support for Specification Extensions everywhere.

I am going to ignore it entirely for now (so that decoding succeeds) but I do like your idea of a warning so it is not super confusing to anyone who goes looking for their Links and finds no explanation for why they are missing.

WIP: https://github.com/mattpolzin/OpenAPIKit/tree/bugfix/ignore-unimplemented-links

**Comment by mattpolzin** [comment]
@mbarnach You should be able to decode documents even if OpenAPIKit does not yet support them with [v1.4.4](https://github.com/mattpolzin/OpenAPIKit/releases/tag/1.4.4)

**Comment by mbarnach** [comment]
It works fine thanks!
One minor issue or missing step, in some way related, is the usage of `Link` in a header. 
The RFC 5988 describes the usage of `link` in headers, and it is used also by [Github](https://github.com/github/rest-api-description). It shouldn't require a `x-` prefix in that case. It is not stated explicitly by OpenAPI (as far as I can tell), but the  online editor accepts them and show them correctly.
Do you think it would be possible to have the exception for them also? Thanks!

**Comment by mattpolzin** [comment]
What you've actually uncovered using the GitHub API is that the Parameter Object and Header Object should both support the `example` and `examples` properties. The Parameter Object already supports example/examples. The Header Object has a bug which I am tracking [here](https://github.com/mattpolzin/OpenAPIKit/issues/107) now.

Thanks for another good find; relatedly, the GitHub OpenAPI documentation is going to be an excellent addition to the OpenAPIKit Compatibility Suite once I get this bug fixed!

**Comment by mattpolzin** [comment]
Latest bug fix went out with [v1.4.5](https://github.com/mattpolzin/OpenAPIKit/releases/tag/1.4.5), although unfortunately OpenAPIKit still cannot decode the GitHub API due to another (unrelated) bug that I had not encountered before; that bug is tracked [here](https://github.com/mattpolzin/OpenAPIKit/issues/111).

**Comment by mbarnach** [comment]
That's great! I have an attempt to add the Github API and all the examples of OpenAPI specifications.
Currently, I load them from URL, which is not what is done elsewhere. I will push it, so you can have a look at it and we can correct/adjust if needed.

**Comment by mattpolzin** [comment]
@mbarnach you may have noticed, but the version 2 release branch of OpenAPIKit now includes the GitHub API in its compatibility suite. Adding that API the the compatibility suite brought to light a couple of bugs in OpenAPIKit and additionally 1 ambiguity in the GitHub API documentation which they have since fixed.

Thanks again for bringing the GitHub OpenAPI documentation to my attention and pushing for it being included in the Compatibility Test Suite!

**Comment by mattpolzin** [comment]
This will be a part of `v3.0.0-alpha.3` and the 3.0.0 stable release once we get there.
