### ISSUE TITLE
Testing examples against implementation

### ISSUE THREAD

**Issue by mbarnach** [mattpolzin/OpenAPIKit#105]
When creating an OpenAPI specifications, one can specify the example.
Testing the example against the real implementation could be interesting.
But, due to the usage of `AnyCodable` this is not quite straightforward.
Currently, I can only decode into `AnyCodable`, but not in any "real" object.

How could we write something like:

Pseudo-code:

```swift
if let example = openAPIDocument.components.examples["some_component"]?.value {
  do {
    let object = try JSONDecoder.decode(SomeComponent, from: example)
    // Do something with the object decoded...
  } catch {
    print("Error: cannot decode the object: examples and implementation don't match")
  }
}
```

**Comment by mattpolzin** [comment]
This is a _really_ intriguing use-case; I've been testing examples against the specified schema of OpenAPI documents at my work place for a while now and it is a really nice and relatively easy consistency check. As you note, there's no straight forward way to do this built into `Codable` or `AnyCodable`.

The easiest (and somehow most straight forward) path is actually to go _back_ through `Codable`. At one point I had some code that used this kind of trick (albeit for a different purpose) in OpenAPIKit but I moved it out into `OpenAPIReflection` to separate concerns a bit and leave the slightly hacky feeling stuff (encode in order to decode again) out of OpenAPIKit.

```swift
let encoder = JSONEncoder()
let decoder = JSONDecoder() // make sure to match encoder/decoder options around casing and date handling etc.
if let example = openAPIDocument.components.examples["some_component"]?.value {
  do {
    let json = try encoder.encode(example)
    let object = try decoder.decode(SomeComponent, from: json)
    // Do something with the object decoded...
  } catch {
    print("Error: cannot decode the object: examples and implementation don't match")
  }
}
```

**Comment by mbarnach** [comment]
Thanks for the trick. I can use it for now. It is always a bit hacky to play with `Codable` and generics. I can almost always do what I want/need to, but never quite so (like loop around types...).
