### ISSUE TITLE
Validating against the schema

### ISSUE THREAD

**Issue by mbarnach** [mattpolzin/OpenAPIKit#153]
It would be very interesting to be able to validate a user request against the schema.
Eg. if we describe the endpoint `/pets` with some query parameters, like `limit` like that:
```json
paths:
  /pets:
    get:
      summary: List all pets
      operationId: listPets
      tags:
        - pets
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
```

Being able to check that doing: curl GET 'http://localhost:8080/pets?limit=10' is a valid request, and `curl GET 'http://localhost:8080/pets?limit=nil'` is not could be a fantastic options in "gatewaying" any server defined by OpenAPI.

I know this is quite huge, but if some ground work is set, I would be more than happy to contribute to it, like adding the regular expression check for fields or different type of casting.
I understand that the primary goal of this library is to generate an OpenAPI specification, but I think there is a lot to gain by ensuring that a specification match the implementation (the other way around, sort of).

**Comment by mattpolzin** [comment]
Request validation (or response validation, for that matter) is a really fantastic use of OpenAPI. You're right, it's a large undertaking, but I think more to the point it feels sufficiently separable from the core purpose of OpenAPIKit that I think it belongs in its own library. It's one of many _uses of OpenAPI documentation_ as opposed to being something that facilitates getting information out of or directly manipulating OpenAPI documentation (which is what OpenAPIKit is all about).

It's worth thinking about the following questions regardless of where the work is done because it drastically changes what the work actually looks like; there also might be other good ways to think about request validation against OpenAPI documentation. Certainly, if you get more domain specific, the problem becomes much more tractable; A project that focused on specifically validating requests that are handled by a particular framework (like Vapor) might be much easier than one that needed to hook into arbitrary projects using any number of web frameworks or stand on its own as a separate service.

Would you imagine this works as a standalone service that you point your requests at to verify they pass the spec but not to actually make real requests against? 

Or do you imagine this being something you can put into a routing system as middleware that rejects requests that don't match the spec and therefore acts as a first defense against malformed requests before those requests reach the actual endpoint that would serve up a response given a valid request?

Or is this a library that requires the user of the library to do some lifting to turn an API request into a representative type that this validation library offers up so the library can perform validation on some AST representing a request instead of worrying about the actual networking details?

For a while now there have been tools to generate API clients or servers based on OpenAPI Documentation (like [SwagGen](https://github.com/yonaskolb/SwagGen)) -- one possible path to what you are talking about would be to make the server code generated by such tools more robust (better at validating requests).

A totally separate approach would be to avoid code generation and instead make the validation a standalone server with the only responsibility being to validate requests it gets. No code generation, but a much narrower focus than the first option.

**Comment by mbarnach** [comment]
As you mention it, there is potentially a lot of applications.
I was thinking of one: if we want to validate the example provided with the specifications, we can abstract away that feature: a `String` that matches the current route/endpoint.
Then, this could be used by any 3rd party approach, either as a middleware or as a standalone application.

For the generator, this is something I've looked into, but I don't think we need that feature for that. It could be a plus, especially if we could generate "random" data that match the specifications (but this is definitively out of scope!).

For the validation as an external library, it could work also. I think we can use Foundation for the URL approach, to be server agnostic. I imagined an external application, that only validate your request, and forward it to another server/port if it matches.
In my wildest dream, it could also have a development mode, where, you get the sample request if the request failed (to tell you how it should work). You then get a way to discover all API using OpenAPI: the gateway is like a mocup server, but with explanations/interactive mode.

If you believe it would be better out of OpenAPIKit, could you share an idea/skeleton of how you envision this? Maybe using `AnyEncodable` approach? Or plain `String`? Ideally an entry point to the library, like `validate(input: String, against: Endpoint)-> Bool` which would allow anyone to use it?

**Comment by mattpolzin** [comment]
I think there is some complexity to uncover before talking about the best way to go about the project.

#### Things to Validate
In your original post, you mentioned a couple of cURL calls that clearly indicated this validation service should validate the query parameters of the request are valid; that's one input to the validation, then. 

I imagine if you are validating query parameters, you also want to validate path, header, and cookie parameters. 

Path parameters and query parameters could arguably be 1 String input to your validation function but it will be best to split them up and consider them more granularly as soon as possible because you're going to need to perform a fair amount of logic on the query parameter portion of the string depending on the expected schema for the query parameters (as dictated by the particular OpenAPI documentation you are validating against).

Headers and cookies will necessarily be separate inputs to your validation because they do not originate as part of the "URL" string.

Then there's the request body (if you want to validate that as well).

Finally, you may wish to validate the authentication method of the request, although theoretically there is another defense against invalid authentication so perhaps this is only particularly useful in the "mock server" capacity you were describing.

#### Complexity
Now that we are talking about the separate inputs to your validation (regardless of whether you write it as a standalone service or as a library), we can dig into each a little deeper.

I'll start with the request body. You'll need to implement some logic that takes the `JSONSchema` from the OpenAPI documentation and crawls some arbitrary input JSON data to determine if it follows the rules of the schema. This is no small task but it's certainly doable (and it has been implemented by numerous other libraries in other languages if not in Swift). If you wanted to pass this part of the task off to another tool, there are plenty of options -- for example, you could have `AJV` (a very good data validator written in Javascript) do the request body validation for you if you didn't want to write it yourself in Swift. I've written request body validation in Swift before, but I went a roundabout way and wrote code that generated `Codable` Swift structures that could then be used to parse a request body and the failure of those structures to parse the request body was equivalent to a failure to match the required schema.

Next the path parameters. Of the various parameters, these are easiest by a bit because the structure of the path is predetermined and path parameters are always required (not optional). You still probably want to be able to consider path parameters to have types determined by the OpenAPI documentation so you can allow an API author to dictate that a path parameter is either an `integer` or a `string` and within strings you may have a regex pattern to consider for validation purposes.

Then there's the rest of the parameters. Validating header & query parameters is a general problem I have wanted to tackle in some capacity for a while but I've never found the time to dig in -- there's a lot of complexity there because of how many ways parameters are allowed to be specified. See the [appropriate section](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameter-object) of the OpenAPI specification for details and take a look at how much variety can be represented by a schema and a style.

Security schema validation is similar to parameter validation in that you need to be able to accept a _lot_ of variety when it comes to what OpenAPI documentation states is allowed for authentication/authorization. Again, the OpenAPI specification has the details on this.

#### Implementation
Now it's worth talking about how to implement a service that performs all of this validation logic.

A common thread runs through all of the above validation concerns: The OpenAPIKit library exposes all the necessary information about the OpenAPI documentation and even resolves some of it making it easier to work with, but it does not get you very far when you are looking to validate data against the OpenAPI documentation -- that's a whole other project.

At this point, with some idea of the pieces of the puzzle that is "validating a request against OpenAPI documentation," it might make sense to research other tools out there that do some or all of the same things. These tools will likely provide insight into how you want to go about your project even though they are mostly if not all written in different languages. This website is a great resource for this type of research: https://openapi.tools.

Then, the next thing I would do (personally) is pick an interesting piece of the puzzle to work on first. I'd start with something like **parameter validation** or **request body validation** and start writing down the abstractions in Swift and then it's all just one foot in front of the other from there!

#### Final Thoughts
This is a truly huge project, like on the scale of OpenAPIKit itself, which was and will continue to be a large effort for me to write and maintain. Perhaps my most salient takeaway is that something like request validation is a fantastic goal but you will probably have the most success (and fun!) if you break the task down and tear off a much smaller problem first; then, you can build out the whole larger service using the smaller pieces you've built along the way. It's perfectly reasonable (and already very useful) to have a library that only worries about parameter validation or only worries about request body validation on your way to a bigger end goal.

The other takeaway might be to either decide you want to tackle this problem for a very specific subset of requests (maybe the ones relevant to you right now) or else spend some time up front really studying the OpenAPI specification because there are a _lot_ of things to consider when validating that something matches its documentation. I've started a number of projects in the former way: I initially ignored a lot of complexity by focusing on just what was useful to me at the time and then I later filled in the rest to make the project more generally applicable.

**Comment by mbarnach** [comment]
Thanks for the very good guidance.

From your suggestion, I think what makes the most sense for me (right now), is:

- Starts with mandatory parameters first: do we have everything we expect (even before knowing if what we have is OK).
- Focus on body and parameters checking:
  - Using Codable to validate the structures is great, but requires to have a 2 stages approach: generate the codable and compile your "gateway". Not sure if this is really suitable, but I will think more about it.
  - Let authentication and security aside for now, as they are the more "critical": if you said they are right, they must be right!
  - Address mostly (only?) the specifications I have now, and let other suggest improvements?
- Try to be server framework agnostic to reach more people. Ideally no dependencies apart from Foundation and OpenAPIKit.

Maybe this is too ambitious, maybe a smaller subset could do. I will see how far I have the time to go!
Again thanks for the guidance!

**Comment by mattpolzin** [comment]
Sounds like a great project. I’ll keep an eye out. Feel free to hit me up again. I’ve gotten quite busy recently but I’d love to see this become a reality!
