### ISSUE TITLE
EXC_BAD_ACCESS when resolving k8s API spec v1.15

### ISSUE THREAD

**Issue by t089** [mattpolzin/OpenAPIKit#171]
macOS 10.15.7
Swift 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
OpenAPIKit at 2.3.0

1. Get Kubernetes API swagger spec and convert to OpenApi v3:
```bash
docker run -it -v $(pwd):/wd -w /wd swaggerapi/swagger-codegen-cli-v3 \
            generate -l openapi \
            -i https://raw.githubusercontent.com/kubernetes/kubernetes/release-1.15/api/openapi-spec/swagger.json \
            -o /wd
```
2. Load `openapi.json` with `OpenAPIKit` and try to resolve the document:
```swift
import OpenAPIKit
import Foundation

let decoder = JSONDecoder()
let data = try Data(contentsOf: URL(fileURLWithPath: "openapi.json"))
let doc = try decoder.decode(OpenAPI.Document.self, from: data)
let resolvedDoc = try doc.locallyDereferenced().resolved()
```
3. Run the app and observe an `EXC_BAD_ACCESS` in `Components.swift` line 85.

**Comment by mattpolzin** [comment]
@t089 thanks for the report. I've located the problem, but at face value the solution won't help you resolve all references in that document. I am afraid that for the foreseeable future of OpenAPIKit, you cannot dereference/resolve that particular document as-is.

The problem is an infinite loop while dereferencing because `#/components/schemas/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps` refers to itself. This is not really a "problem" (as far as I know, it is a perfectly reasonable JSON Schema), but it does pose an interesting challenge to OpenAPIKit's dereferencing logic.

I think one thing that will definitely help is adding cycle detection to the dereferencing logic so the error is planned instead of the program just running out of stack space.

Then we are left with the question of whether there is a useful solve here beyond just "this document cannot be fully dereferenced." I am tempted to say that this warrants a new type of construct in a dereferenced context wherein a cycle can be explicitly represented instead of resulting in failure to dereference. That way, you can deference the document in all ways _except_ for the cycle. That part deserves more thinking.

**Comment by t089** [comment]
Nice, thanks for the explanation. So, for now I cannot dereference this document. Can I still practically iterate over it?

**Comment by mattpolzin** [comment]
You can still iterate over it, you are just limited to the OpenAPI representation of the document in a very literal sense; the dereferencing and resolving steps can make certain tasks easier but they don’t fundamentally expose any new information you cannot access by inspecting the result of decoding the document into OpenAPIKit’s types. 

I realize I am being vague; can you give me a bit more information about what you are trying to do? I’d be happy to offer suggestions as to how to use OpenAPIKit for your use-case.

**Comment by t089** [comment]
Thanks, I was just starting to look into it. I am interested in bootstrapping a client implementation for the k8s api (or subset of it). So I want to generate code for some/all of the api endpoints.

**Comment by mattpolzin** [comment]
Sounds great! You can definitely do that without a dereferenced and resolved document. Given:
```swift
let doc = try decoder.decode(OpenAPI.Document.self, data)
```

You could (for starters) loop over all endpoints the document describes printing their parameters:
```swift
for route in doc.routes {
    let routeParams = route.pathItem.parameters
    for endpoint in route.pathItem.endpoints {
        let endpointParams = endpoint.operation.parameters

        let allParams = try (routeParams + endpointParams)
            .map(doc.components.lookup)

        if allParams.isEmpty {
            print("No parameters for \(endpoint.method.rawValue) \(route.path.rawValue).")
        } else {
            let paramsDict = Dictionary(grouping: allParams) { $0.location }

            print("parameters at \(endpoint.method.rawValue) \(route.path.rawValue): ")
            for (location, params) in paramsDict {
                for param in params {
                    print("\(param.name) (\(location.rawValue))")
                }
            }
        }
    }
}
```

For example:
```
parameters at GET /apis/storage.k8s.io/v1beta1/csinodes: 
pretty (query)
allowWatchBookmarks (query)
continue (query)
fieldSelector (query)
labelSelector (query)
limit (query)
resourceVersion (query)
timeoutSeconds (query)
watch (query)
parameters at POST /apis/storage.k8s.io/v1beta1/csinodes: 
pretty (query)
dryRun (query)
fieldManager (query)
parameters at DELETE /apis/storage.k8s.io/v1beta1/csinodes: 
pretty (query)
allowWatchBookmarks (query)
continue (query)
dryRun (query)
fieldSelector (query)
gracePeriodSeconds (query)
labelSelector (query)
limit (query)
orphanDependents (query)
propagationPolicy (query)
resourceVersion (query)
timeoutSeconds (query)
watch (query)
...
```

From here, take a look at the [documentation](https://github.com/mattpolzin/OpenAPIKit/wiki) for `OpenAPI.Document`, `OpenAPI.PathItem`, `OpenAPI.Operation`, and `OpenAPI.Parameter` to get a sense for the other API properties exposed just in the vicinity of my example code above. 

Digging deeper, you might access the schema of the parameters and you might end up pulling apart the `OpenAPI.Request` and `OpenAPI.Response`s found on each operation to look at their schemas.

**Comment by mattpolzin** [comment]
In my example code above, there are two things perhaps particularly worth pointing out:
1. I use `doc.components.lookup()` to go from an array of `Either<Parameter>` to just `Parameter`; this is going to be a common thing in a document that is _not_ dereferenced because this is a localized lookup of a (potential) reference. This is what fully dereferencing the document does, but it does so greedily which causes problems when you hit cyclic references.
2. I combine any parameters found on the `OpenAPI.PathItem` with those found on the `OpenAPI.Operation` -- OpenAPI allows documentation to specify parameters that work for all endpoints on a route and those that only work on one endpoint separately, so you need to combine them to get the whole picture for an endpoint. This is another thing that resolving a document does for you, so you must do a bit of extra legwork because the document cannot be fully dereferenced in this case.
