### ISSUE TITLE
Distribute via CocoaPods?

### ISSUE THREAD

**Issue by liamnichols** [mattpolzin/OpenAPIKit#253]
Hey! Great tool! I’m just wondering if you’d consider distributing it via CocoaPods? 

I can submit a pull request with the podspec and anything else you require to help if you are interested but I just wanted to check first.

Thanks!

**Comment by mattpolzin** [comment]
Thank you for the offer. I don't plan on maintaining two separate package manifests (or keeping versions in sync or publishing to alternative package platforms) for OpenAPIKit. I've done this before with other projects but because Swift Package Manager is pretty well established I would like to stick with just the one offering for this library.

My suggestion, if you really need to vendor this via CocoaPods, would be to add a podspec to your own fork of the repository. I know that's not the same at all, I'm just not up for maintaining the podspec myself at this point.

**Comment by liamnichols** [comment]
Thanks for confirming @mattpolzin! That's fine 🙂 I saw that you had done it with other projects so it did cross my mind that there might be a specific reason for not supporting it here. 

> My suggestion, if you really need to vendor this via CocoaPods, would be to add a podspec to your own fork of the repository. I know that's not the same at all, I'm just not up for maintaining the podspec myself at this point.

I'll do that until we decide to move towards SPM 🙂 Thanks again 🚀
