### ISSUE TITLE
Incorrect decoding of `type: null` from Yaml

### ISSUE THREAD

**Issue by brandonbloom** [mattpolzin/OpenAPIKit#364]
This test exists:

```
    func test_decodeNullType() throws {
        let nullTypeData = """
        {
          "type": "null"
        }
        """.data(using: .utf8)!

        let decoded = try orderUnstableDecode(JSONSchema.self, from: nullTypeData)

        XCTAssertEqual(decoded, .null())
    }
```

However, adding a similar test for Yaml highlights the bug:

```diff
diff --git a/Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift b/Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift
index 12c7c10c..1d32f5d7 100644
--- a/Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift   
+++ b/Tests/OpenAPIKitTests/Schema Object/SchemaObjectYamsTests.swift   
@@ -16,6 +16,20 @@ import OpenAPIKit
 import Yams
 
 final class SchemaObjectYamsTests: XCTestCase {
+    func test_nullTypeDecode() throws {
+        let nullString =
+        """
+        type: 'null'
+        """
+
+        let null = try YAMLDecoder().decode(JSONSchema.self, from: nullString)
+
+        XCTAssertEqual(
+            null,
+            JSONSchema.null()
+        )
+    }
+
     func test_floatingPointWholeNumberIntegerDecode() throws {
         let integerString =
         """
```

In short, `nil` is returned, when `JSONType.null` is expected.

**Comment by brandonbloom** [comment]
I've been looking at this a little more and have narrowed the problem down to `decodeIfPresent` for `JSONType`. This is used in a few places (`decodeNullable` and `decodeTypes`) and behaves incorrectly for `type: null` and `type: 'null'`. Interestingly, `container.contains(.type) ? container.decode(JSONType.self, forKey: .type) : nil` works as expected.

**Comment by mattpolzin** [comment]
So this is actually related to a Yams bug that has been fixed as of version `5.1.0` of Yams. I had purposefully avoided writing a test for Yams decoding similar to the one you wrote because I knew it would not pass. Now that Yams `5.1.0` is released, it can be added (and passes): https://github.com/mattpolzin/OpenAPIKit/pull/365

Interestingly, the Yams fix also [only works for Swift releases later than 5.4](https://github.com/mattpolzin/OpenAPIKit/actions/runs/8500959829/job/23283372186?pr=365), it appears. A bit surprising. That means that I can't bump the locked version of Yams for the project prior to OpenAPIKit 4.0.0.

Here's a little more background: https://github.com/apple/swift-openapi-generator/issues/286#issuecomment-1749127706. In that comment, you can focus on the second paragraph where I explain and link to a Yams bug that describes the behavior you've described in the OP for this issue.

**Comment by mattpolzin** [comment]
I see you came to the same conclusion as I was typing up my response!

**Comment by mattpolzin** [comment]
Your PR looks good to me if you rebase it against `release/4_0`.

**Comment by brandonbloom** [comment]
Rebase: Done.
