### ISSUE TITLE
Add ability to validate an OpenAPI document

### ISSUE THREAD

**Issue by siemensikkema** [mattpolzin/OpenAPIKit#79]
Despite the strictness of the type system there are still ways to create invalid documents, for example:
- creating a PathItem with zero operations
- a Document with zero paths

It can sometimes be useful to have a document that is not yet fully valid when you are still “building” on it. Therefore we should not perform any runtime checks in initializers in an attempt to block the user from making any invalid document.
Rather (as we have discussed on Discord) we could look into adding a throwing`validate` method. This should collect all validation errors into a compound error value. The return type could be different type describing a valid document which can only be made by the validate method. Maybe `ValidatedDocument` which wraps a document and has an initializer that is only available to the validation method.

**Comment by mattpolzin** [comment]
The part of this that I've been doing a bit of thinking on is `ValidatedDocument`. I was considering doing something similar for dereferencing (i.e. taking `JSONReferences` and resolving them to the referenced types to remove all of the `Either<Reference, Thing>` types in the AST). I was going to use names like `ResolvedWhatever` for a type that are equivalent to `Whatever` except for replacing `Either<Reference, Thing>` properties with `Thing` properties.

The reason this comes up is because I wonder if it makes sense to use new types for both (and are there other similar reasons we may want new types?). Do we quickly devolve into a mess where you have `Whatever`, `ValidatedWhatever`, `ResolvedWhatever`, and `ValidatedResolvedWhatever`?

Maybe it's a non-issue; perhaps we only need `ValidatedDocument` (no need to subtype everything along the way) and perhaps more often than it making sense for there to be a one-to-one relationship between `Whatever` and `ResolvedWhatever` it will make more sense to only offer the resolved types as the "canonical" representations I mentioned [here](https://github.com/mattpolzin/OpenAPIKit/issues/4).

Something to keep mulling on a bit more.

**Comment by mattpolzin** [comment]
i had a thought tonight. I wonder if it is worth using `Encodable` to facilitate this validation system. Instead of hardcoding a few validations into some types (like the examples brought up in the original post for this Issue), OpenAPIKit could offer open-ended validation support and package a few prebuilt validations for the aforementioned checks.

I've explored this type of idea before with [TransformEncoder](https://github.com/mattpolzin/TransformEncoder). Basically, we could build an "encoder" that can be given any number of validators; each validator takes a particular Type to a validation result (success or any number of errors). The "encode" operation is actually just to check for any validators that operate on the type being "encoded" and run them against it. The benefit to using `Encodable` becomes the built-in traversal of the whole OpenAPI document and the built-in location awareness via CodingKey paths.

**Comment by siemensikkema** [comment]
That's some lateral thinking, I love it :D I'm curious to see if it works in practice

**Comment by mattpolzin** [comment]
A nice thing about any open ended approach (whether based on `Encodable` or not) is that it can simultaneously fill the holes in validation you describe in this Issue and also allow end users to add arbitrary rules (not dictated by OpenAPI but nevertheless required by their org). My company does this using meta-schema validation via AJV right now, but doing it with the help of clarity and conciseness that comes with the Swift type system instead of relying on JSON Schema definitions would probably be welcome!

**Comment by mattpolzin** [comment]
Experimenting with this over at https://github.com/mattpolzin/OpenAPIKit/pull/80.

So far, some pretty intriguing results, although I would not say I have settled on this API.

As an example, to validate that `PathItem` has at least one `Operation`, you could use:
```swift
let document = OpenAPI.Document(...)

try document.validator
    .validating(\OpenAPI.PathItem.endpoints.count > 0)
    .assertValidity()
```

Or to get a more appealing descriptive string:
```swift
let document = OpenAPI.Document(...)

try document.validator
    .validating("Path Items must have at least one Operation") { (context: ValidationContext<OpenAPI.PathItem>) in
        context.subject.endpoints.count > 0
}
    .assertValidity()
```

And you can apply preconditions too so you could assert that "if the test server is specified, there must be at least two servers specified.":
```swift
try document.validator
    .validating(
        \.document.servers.count > 1,
        if: \OpenAPI.Server.url == URL(string: "https://test.server.com")!
    ).assertValidity()
```

The syntax is a bit clunky in these examples, but you can store the validator and pass it around this way and you can chain as many `validating(...)` calls as you want before calling `assertValidity()` to apply any number of validations.

**Comment by siemensikkema** [comment]
That looks insanely cool! I like that this allows you to add any kind of custom validation. I would also like to be able to quickly validate a document according to the official specs (ie. the document passes a linter). Then you could build on top of that with your own rules. This could look like:

```swift
try document.validator
  .validatingOpenAPISpec(.version3_0_3)
  .validating( ... )
  .assertValidity()
```

**Comment by mattpolzin** [comment]
Ah, I think that looks nice. I was picturing there being a default set of validations to meet the spec and requiring the user to actually “clear” them on a validator instance if they really wanted to not use them.

```swift
document.validator // automatically validated the spec including rules not represented by the type system. 

document.validator.empty // no validations outside of what you get from the type system and encoders; probably not really very useful outside of unit testing. 
```

I am drawn to your idea of adding validations by specifying a version of the spec, but also wondering if newer versions of the spec (other than major versions like 4.x) would really ever warrant rules not applicable to previous versions. Minor version bumps to the spec aught to be non-breaking and therefore cannot retroactively become more strict. Perhaps that is only true in theory, though.

**Comment by mattpolzin** [comment]
phew. getting there. I feel close _enough_ that I've done a good bit of documentation here: https://github.com/mattpolzin/OpenAPIKit/blob/9831a2bbe2c4d419d5632f255ad1242f45ec41fb/documentation/validation.md

A point of interest: The two validations listed as motivation for this ticket (that I definitely thought made sense) are actually still going to be optional (although they are built-in) because the OpenAPI Specification actually calls out the fact that documents without paths or paths without operations are allowed for [security reasons](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#security-filtering). I found a couple other nice validations to add in as defaults still and I am sure there are 5-10 other validations that should be added as default once I've re-read the whole specification.

**Comment by mattpolzin** [comment]
ok, quite a bit of things (small syntactically and large feature-wise) have changed since the last comment, but the documentation is up to date and even a lot more robust now and I am feeling like as far as this experiment goes I am probably closing in on a PR I like: https://github.com/mattpolzin/OpenAPIKit/pull/80

Certainly worth soliciting feedback on it at this point. I am also going to explore some more advanced validations I have in mind for personal projects of mine to see if I uncover any more glaring holes in what this can do.

**Comment by siemensikkema** [comment]
@mattpolzin Very very nice, I think you're really onto something here!
Another validation issue I ran into recently was the misspelling of "bearer" as "Bearer". Such things should be easy to validate against with this validation system.
I guess we could also have a validation rule that states that returned objects are never top-level but wrapper in a "data" object. I'll see if I can get some time to play with it soon ...
